In [2]:
import numpy as np
import sklearn

In [9]:
class Node:
    def __init__(self, inputs=[]) -> None:
        self.inputs = inputs
        self.outputs = []
        for n in self.inputs:
            self.outputs.append(n)
            print(self.outputs)
        self.value = None
        self.gradient = {}
    
    def forward(self):
        raise NotImplemented

    def backward(self):
        raise NotImplemented

In [10]:
node = Node(inputs=[1,2,3])

[1]
[1, 2]
[1, 2, 3]


In [9]:
a = np.array([1,2,3])
a[:,np.newaxis].repeat(repeats=2, axis=1)

array([[1, 1],
       [2, 2],
       [3, 3]])

In [9]:
from sklearn.preprocessing import OneHotEncoder

np.random.seed(42)
a = np.random.rand(6,3)
print(a)
print(np.exp(a))
print(np.sum(np.exp(a), axis=1))
print(np.exp(a)/np.sum(np.exp(a), axis=1)[:, np.newaxis])

b = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[11]])
enc = OneHotEncoder(max_categories=11, sparse=False)
enc.fit_transform(b)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]
[[1.45432245 2.58755731 2.07922233]
 [1.81967604 1.16884799 1.1688198 ]
 [1.0598036  2.37780108 1.82415162]
 [2.03007467 1.02079782 2.63770667]
 [2.29892734 1.23656715 1.19940424]
 [1.20130025 1.3555974  1.69004716]]
[6.12110208 4.15734383 5.2617563  5.68857916 4.73489873 4.2469448 ]
[[0.2375916  0.42272736 0.33968104]
 [0.4377016  0.28115259 0.28114581]
 [0.20141632 0.45190255 0.34668113]
 [0.35686849 0.17944689 0.46368462]
 [0.4855283  0.26116021 0.25331149]
 [0.28286222 0.31919355 0.39794422]]


/home/re6111032/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
list(range(1,12))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [30]:
np.array([[i] for i in range(1, 12)]).shape

(11, 1)

In [3]:
import numpy as np

np.array([[1,2,3],[4,5,6]])*np.array([[4,5,6],[7,8,9]])

array([[ 4, 10, 18],
       [28, 40, 54]])

In [13]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
# np.exp(a)/np.sum(np.exp(a))
a/np.sum(a, axis=1).reshape(-1,1)

array([[0.16666667, 0.33333333, 0.5       ],
       [0.26666667, 0.33333333, 0.4       ]])

In [12]:
import numpy as np

w = np.random.uniform(-0.5,0.5,(6,3))
print(w)
print(np.exp(w))
# print(np.exp(w)/np.sum(np.exp(w), axis=1, keepdims=True))
print(np.sum(np.exp(w), axis=1, keepdims=True))

[[-0.37861729 -0.40419389  0.48481702]
 [ 0.10381952  0.31669449 -0.27432114]
 [-0.3295814  -0.12224979 -0.05920088]
 [-0.03496111  0.22330603  0.00610143]
 [ 0.48870107 -0.04054952  0.25355546]
 [-0.0999167  -0.07541061 -0.45447379]]
[[0.68480765 0.66751469 1.62387785]
 [1.10940021 1.37258317 0.76008794]
 [0.71922473 0.88492729 0.94251742]
 [0.96564297 1.25020312 1.00612008]
 [1.63019733 0.96026161 1.28859884]
 [0.9049128  0.92736262 0.63478191]]
[[2.97620018]
 [3.24207132]
 [2.54666945]
 [3.22196617]
 [3.87905778]
 [2.46705733]]


In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [46]:
def onehot(label, n_classes):
    enc = np.zeros(shape=(len(label), n_classes))
    for idx, val in enumerate(label):
        enc[idx, val] = 1
    return enc

y = [[0],[1],[2],[3],[4],[5]]
onehot(y,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [35]:
list(zip(np.arange(len(y)), y.__getitem__()))

TypeError: list.__getitem__() takes exactly one argument (0 given)

In [37]:
y.__getitem__(0).__getitem__(0)

0

In [41]:
list(zip(np.arange(len(y)), [y.__getitem__(i).__getitem__(0) for i in range(len(y))]))

[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]

In [120]:
np.random.seed(42)
print(np.random.uniform(-1,1,2))

print(45)

# np.random.seed(42)
print(np.random.uniform(-1,1,2))

[-0.25091976  0.90142861]
45
[0.46398788 0.19731697]
